language: c
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service postgresql stop; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 PINS="deriving:https://github.com/ocsigen/deriving.git eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
  - OCAML_VERSION=4.05 PINS="deriving:https://github.com/ocsigen/deriving.git eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
  - OCAML_VERSION=4.06 PINS="deriving:https://github.com/ocsigen/deriving.git eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
os:
  - linux
  - osx
branches:
  only:
  - master