language: c

env: HOW_DOC=doc HOW_CONFIG=how.json HOW_OUT=_doc

install:
    - wget https://ocsigen.org/how.sh
    - . how.sh
    - how-install

script:
    - how-generate
    - how-redirect "$HOW_LATEST/manual/intro" $HOW_OUT/index.html
    - mkdir -p _doc/demo
    - how-redirect "http://ocsigen-1.inria.fr/ocsigen-start/demo/" _doc/demo/index.html
    - how-redirect-manual $HOW_LATEST latest clientserver

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GHP_TOKEN
  local-dir: _doc
  on:
    branch: wikidoc
